package com.arknow.common.exception;

public enum ErrorCode {
    BAD_REQUEST,
    INTERNAL_ERROR,
    IDENTIFIER_EXISTS,
    IDENTIFIER_NOT_FOUND,
    INVALID_CREDENTIALS,
    REFRESH_TOKEN_INVALID,
    TERMS_NOT_ACCEPTED,
    VERIFICATION_NOT_FOUND,
    VERIFICATION_MISMATCH,
    VERIFICATION_TOO_MANY_ATTEMPTS,
    VERIFICATION_RATE_LIMIT,
    VERIFICATION_DAILY_LIMIT,
    PASSWORD_POLICY_VIOLATION
}
